src/Entity/Musique.php
<?php

namespace App\Entity;

use App\Repository\MusiqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: MusiqueRepository::class)]
#[Broadcast]
class Musique
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $style_musique = null;

    #[ORM\OneToMany(mappedBy: 'musique', targetEntity: Concert::class)]
    private Collection $concerts;

    public function __construct()
    {
        $this->concerts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStyleMusique(): ?string
    {
        return $this->style_musique;
    }

    public function setStyleMusique(string $style_musique): static
    {
        $this->style_musique = $style_musique;

        return $this;
    }

    /**
     * @return Collection<int, Concert>
     */
    public function getConcerts(): Collection
    {
        return $this->concerts;
    }

    public function addConcert(Concert $concert): static
    {
        if (!$this->concerts->contains($concert)) {
            $this->concerts->add($concert);
            $concert->setMusique($this);
        }

        return $this;
    }

    public function removeConcert(Concert $concert): static
    {
        if ($this->concerts->removeElement($concert)) {
            // set the owning side to null (unless already changed)
            if ($concert->getMusique() === $this) {
                $concert->setMusique(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->style_musique;
    }
}

src/Form/MusiqueType.php
<?php

namespace App\Form;

use App\Entity\Musique;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MusiqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('style_musique')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Musique::class,
        ]);
    }
}

templates/musique/_delete_form.html.twig
<form method="post" action="{{ path('app_musique_delete', {'id': musique.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ musique.id) }}">
    <button class="btn">Delete</button>
</form>

templates/musique/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/musique/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Musique{% endblock %}

{% block body %}
    <h1>Edit Musique</h1>

    {{ include('musique/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_musique_index') }}">back to list</a>

    {{ include('musique/_delete_form.html.twig') }}
{% endblock %}

templates/musique/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Musique index{% endblock %}

{% block body %}
    <h1>Musique index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Style_musique</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for musique in musiques %}
            <tr>
                <td>{{ musique.id }}</td>
                <td>{{ musique.styleMusique }}</td>
                <td>
                    <a href="{{ path('app_musique_show', {'id': musique.id}) }}">show</a>
                    <a href="{{ path('app_musique_edit', {'id': musique.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_musique_new') }}">Create new</a>
{% endblock %}

templates/musique/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Musique{% endblock %}

{% block body %}
    <h1>Create new Musique</h1>

    {{ include('musique/_form.html.twig') }}

    <a href="{{ path('app_musique_index') }}">back to list</a>
{% endblock %}

templates/musique/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Musique{% endblock %}

{% block body %}
    <h1>Musique</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ musique.id }}</td>
            </tr>
            <tr>
                <th>Style_musique</th>
                <td>{{ musique.styleMusique }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_musique_index') }}">back to list</a>

    <a href="{{ path('app_musique_edit', {'id': musique.id}) }}">edit</a>

    {{ include('musique/_delete_form.html.twig') }}
{% endblock %}