src/Entity/Scene.php
<?php

namespace App\Entity;

use App\Repository\SceneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: SceneRepository::class)]
#[Broadcast]
class Scene
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_scene = null;

    #[ORM\OneToMany(mappedBy: 'scene', targetEntity: Concert::class)]
    private Collection $concerts;

    public function __construct()
    {
        $this->concerts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomScene(): ?string
    {
        return $this->nom_scene;
    }

    public function setNomScene(string $nom_scene): static
    {
        $this->nom_scene = $nom_scene;

        return $this;
    }

    /**
     * @return Collection<int, Concert>
     */
    public function getConcerts(): Collection
    {
        return $this->concerts;
    }

    public function addConcert(Concert $concert): static
    {
        if (!$this->concerts->contains($concert)) {
            $this->concerts->add($concert);
            $concert->setScene($this);
        }

        return $this;
    }

    public function removeConcert(Concert $concert): static
    {
        if ($this->concerts->removeElement($concert)) {
            // set the owning side to null (unless already changed)
            if ($concert->getScene() === $this) {
                $concert->setScene(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->nom_scene;
    }
}

src/Form/SceneType.php
<?php

namespace App\Form;

use App\Entity\Scene;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SceneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_scene')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Scene::class,
        ]);
    }
}

templates/scene/_delete_form.html.twig
<form method="post" action="{{ path('app_scene_delete', {'id': scene.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ scene.id) }}">
    <button class="btn">Delete</button>
</form>

templates/scene/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Scene{% endblock %}

{% block body %}
    <h1>Edit Scene</h1>

    {{ include('scene/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_scene_index') }}">back to list</a>

    {{ include('scene/_delete_form.html.twig') }}
{% endblock %}

templates/scene/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Scene index{% endblock %}

{% block body %}
    <h1>Scene index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_scene</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for scene in scenes %}
            <tr>
                <td>{{ scene.id }}</td>
                <td>{{ scene.nomScene }}</td>
                <td>
                    <a href="{{ path('app_scene_show', {'id': scene.id}) }}">show</a>
                    <a href="{{ path('app_scene_edit', {'id': scene.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_scene_new') }}">Create new</a>
{% endblock %}

templates/scene/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Scene{% endblock %}

{% block body %}
    <h1>Create new Scene</h1>

    {{ include('scene/_form.html.twig') }}

    <a href="{{ path('app_scene_index') }}">back to list</a>
{% endblock %}

templates/scene/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Scene{% endblock %}

{% block body %}
    <h1>Scene</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ scene.id }}</td>
            </tr>
            <tr>
                <th>Nom_scene</th>
                <td>{{ scene.nomScene }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_scene_index') }}">back to list</a>

    <a href="{{ path('app_scene_edit', {'id': scene.id}) }}">edit</a>

    {{ include('scene/_delete_form.html.twig') }}
{% endblock %}